### ISSUE TITLE
npmjs support?

### ISSUE THREAD

**Issue by retorquere** [yatyricky/lua-bundler#1]
Would it be possible to publish this bundler to npmjs for easier installs?

**Comment by yatyricky** [comment]
WOW, never expected this  could be useful to someone else. I feel honored now.
However lua-bundler was only used in one of my abandoned toy projects. I think it's best that you keep using this for like 10 or some days. If it looks stable and really works as expected, then it shall be ready to go npmjs.
What do you think?

**Comment by retorquere** [comment]
I'll give it a go

**Comment by yatyricky** [comment]
Okay, I look forward to your bug reports and feature requests :)

**Comment by retorquere** [comment]
It can't find luarocks-installed files. I hacked around a bit and could have it find my own `require('lunajson')`, but that called `require 'lunajson.decoder'` and that's not found.

**Comment by yatyricky** [comment]
The usage of "require" is strict to `require("lunajson/decoder")` for now. I'll make a quick update.
